spring:
  output.ansi.enabled: always
  application:
    name: isgroup-identity
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:h2:mem:users;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: false
server:
  port: 8080
  servlet:
    context-path: /isgroup-identity
logging:
  level:
    root: INFO
    it.isgroup.identity: DEBUG
  file:
    name: logs/identity.log  
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  
