spring:
  docker:
    compose:
      enabled: true
      file: docker/docker-compose.yaml
      lifecycle-management: start-and-stop
  datasource:
    url: jdbc:postgresql://localhost:5432/users_db
    username: appuser
    password: apppasswd
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  #flyway:
  #  enabled: true
  #  baseline-on-migrate: true