-- V1__init.sql
-- Schema for User + roles (works on PostgreSQL and H2 in PostgreSQL mode)

-- users table
CREATE TABLE users (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username    VARCHAR(50)  NOT NULL,
  email       VARCHAR(255) NOT NULL,
  tax_code    VARCHAR(16),
  first_name  VARCHAR(100),
  last_name   VARCHAR(100),
  CONSTRAINT uk_user_email UNIQUE (email)
);

-- element collection table for roles
CREATE TABLE user_roles (
  user_id BIGINT      NOT NULL,
  role    VARCHAR(20) NOT NULL,
  CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ck_user_roles_valid CHECK (role IN
    ('OWNER','OPERATOR','MAINTAINER','DEVELOPER','REPORTER'))
);

-- helpful indexes
CREATE INDEX idx_users_username  ON users(username);
CREATE INDEX idx_users_email  ON users(email);
CREATE INDEX idx_users_last_name ON users(last_name);
